### ISSUE TITLE
Fix link urls

### ISSUE THREAD

**Issue by carlosrrdev** [carlosrrdev/divvy#5]
## Expectation

There are several links that are missing their urls and need to be added.

## Steps

- ~~Add a link to ko-fi `https://ko-fi.com/carlosrr`. This url needs to be added to the `Donations` button that appears in the `What is Divvy` modal and the heart icon link located in the socials section~~
- ~~Add a mailto link to `contact@crr.codes`. This mailto url should be added to the mail icon link in the socials section~~
- Add link to GitHub profile `https://github.com/carlosrrdev`. This url should be added to the GitHub icon link located in the socials section
- Add link to X (twitter) `https://twitter.com/carlosrrdev`. This url needs to be added to the X icon link in the socials section

**Comment by ryukaizen** [comment]
Can I work on this issue @carlosrrdev?

**Comment by saemirii** [comment]
will work in this as well. the last two points! @carlosrrdev

**Comment by carlosrrdev** [comment]
> Can I work on this issue @carlosrrdev?

Yes! Can you take care of the first 3 link urls please?

**Comment by carlosrrdev** [comment]
> will work in this as well. the last two points! @carlosrrdev 

Perfect! Thank you!

**Comment by carlosrrdev** [comment]
Issue now resolved
#8
